version: '3.1'
services:
  web:
    image: odoo:15.0
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
  db:
    image: postgres:13
    restart: always
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
